import type { Metadata } from "next"
import "./globals.css"
import { Space_Grotesk } from "next/font/google"
import Providers from "./providers"

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Power Timers - Edit",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`page-default ${spaceGrotesk.className}`}>
        <Providers>
          <aside>
            <nav></nav>
          </aside>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
